rare = ["Nita", "Colt", "Bull", "Brock", "El Primo", "Barley", "Poco", "Rosa"]
super_rare = ["Jessie", "Dynamike", "Tick", "8-Bit", "Rico", "Darril", "Penny", "Carl", "Jacky", "Gus"]
epic = [
    "Bo",
    "Emz",
    "Stu",
    "Piper",
    "Pam",
    "Frank",
    "Bibi",
    "Bea",
    "Nani",
    "Edgar",
    "Griff",
    "Grom",
    "Bonnie",
    "Gale",
    "Colette",
    "Belle",
    "Ash",
    "Lola",
    "Sam",
    "Mandy",
    "Maisie",
    "Hank",
    "Pearl",
    "Larry and Lawrie",
    "Angelo",
]
mific = [
    "Mortis",
    "Tara",
    "Max",
    "Mr. P",
    "Byron",
    "Squeak",
    "Buzz",
    "Fang",
    "Eve",
    "Otis",
    "Buster",
    "Gray",
    "R-T",
    "Willow",
    "Charlie",
    "Mico",
    "Lily",
    "Gene",
    "Sprout",
    "Lou",
    "Ruffs",
    "Janet",
    "Doug",
    "Chuck",
    "Melodie",
]
legendary = ["Spike", "Sandy", "Amber", "Chester", "Kit", "Draco", "Crow", "Leon", "Meg", "Surge", "Cordelius"]

rarest = {"Rare": rare, "Super_rare": super_rare, "Epic": epic, "Mific": mific, "Legendary": legendary}
